data:
  save: True
  data_dir: /home/saumyas/experiment_results/object_centric/r3m/data/
  prefix: 'sawyer_mt_gen'
  vary: target
  # These flags are overriden by skill specific flags if provided
  num_demos_per_env_type:
    train: 10
    eval: 10

seed: 8
data_collect_types:
  - train
  - eval
  # - eval_1

object_descriptions_standard:
  milk:
    - 'milk'
  coke:
    - 'coke'
  pepsi:
    - 'pepsi'
  bread:
    - 'bread'
  bottle:
    - 'bottle'
  blockA:
    - 'red block'
  blockB:
    - 'green block'
  blockC:
    - 'blue block'
  blockD:
    - 'yellow block'

object_descriptions_synonyms:
  milk:
    - 'cream carton'
    - 'milk-cream carton'
  coke:
    - 'coca cola'
  pepsi:
    - 'pepsi can'
  bread:
    - 'sourdough'
  bottle:
    - 'tonic'
  blockA:
    - 'red cuboid'
  blockB:
    - 'green cuboid'
  blockC:
    - 'blue cuboid'
  blockD:
    - 'yellow cuboid'

skills:
  use: 'all'
  train:
  # Set use: all to loop through all skills and create one dataset for them
    use: 'all'
    all_skills:
      - 'pick'
      - 'stack'
      - 'pick_and_place'
      - 'push_left'
      - 'push_right'
      - 'push_forward'
      - 'push_backward'
  eval:
    use: 'all'
    all_skills:
      - 'pick'
      - 'stack'
      - 'pick_and_place'
      - 'push_left'
      - 'push_right'
      - 'push_forward'
      - 'push_backward'

train:
  only_use_block_objects: False
  pick:
    skill_desc: "Pick"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      - 'coke'
      - 'milk'
      - 'bread'
      - 'bottle'
  stack:
    skill_desc: "Stack"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      # - 'blockD'
    stack_on_objects:
      - 'blockA'
      - 'blockB'
      # - 'blockC'
      - 'blockD'
  pick_and_place:
    skill_desc: "Pick and place"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      # - 'blockD'
      - 'coke'
      - 'milk'
      - 'bread'
      - 'bottle'
  push_left:
    skill_desc: "Push to the left"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      # - 'blockD'
      - 'coke'
      - 'milk'
      - 'bread'
      - 'bottle'
  push_right:
    skill_desc: "Push to the right"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      # - 'blockD'
      - 'coke'
      - 'milk'
      - 'bread'
      - 'bottle'
  push_forward:
    skill_desc: "Push forward"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      # - 'blockD'
      - 'coke'
      - 'milk'
      - 'bread'
      - 'bottle'
  push_backward:
    skill_desc: "Push backward"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      # - 'blockD'
      - 'coke'
      - 'milk'
      - 'bread'
      - 'bottle'
  all_blockA_colors:
    - red
  all_blockB_colors:
    - green
  all_blockC_colors:
    - blue
  all_blockD_colors:
    - yellow
  all_coke_colors:
    - red
  all_pepsi_colors:
    - blue
  all_milk_colors:
    - white
  all_bread_colors:
    - brown
  all_bottle_colors:
    - green
  all_block_sizes:
    - medium
  object_description: ${object_descriptions_standard}

eval:
  only_use_block_objects: False
  pick:
    skill_desc: "Pick"
    target_objects:
      - 'blockD'
      - 'pepsi'
  stack:
    skill_desc: "Stack"
    target_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      - 'blockD'
    stack_on_objects:
      - 'blockA'
      - 'blockB'
      - 'blockC'
      - 'blockD'
  pick_and_place:
    skill_desc: "Pick and place"
    target_objects:
      - 'blockD'
      - 'pepsi'
  push_left:
    skill_desc: "Push to the left"
    target_objects:
      - 'blockD'
      - 'pepsi'
  push_right:
    skill_desc: "Push to the right"
    target_objects:
      - 'blockD'
      - 'pepsi'
  push_forward:
    skill_desc: "Push forward"
    target_objects:
      - 'blockD'
      - 'pepsi'
  push_backward:
    skill_desc: "Push backward"
    target_objects:
      - 'blockD'
      - 'pepsi'
  all_blockA_colors:
    - red
  all_blockB_colors:
    - green
  all_blockC_colors:
    - blue
  all_blockD_colors:
    - yellow
  all_coke_colors:
    - red
  all_pepsi_colors:
    - blue
  all_milk_colors:
    - white
  all_bread_colors:
    - brown
  all_bottle_colors:
    - green
  all_block_sizes:
    - medium
  object_description: ${object_descriptions_standard}
